name: CI - Tarea 7

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar el repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurar el entorno de C++
      - name: Set up C++ environment
        uses: actions/setup-cpp@v1
        with:
          compiler: gcc

      # 3. Instalar dependencias necesarias (CMake, GoogleTest, LCOV)
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake lcov

      # 4. Configurar y compilar el proyecto
      - name: Configure and build
        run: |
          cd Tarea7
          mkdir build
          cd build
          cmake ..
          make

      # 5. Ejecutar pruebas
      - name: Run tests
        run: |
          cd Tarea7/build
          ./testInventario
          ./testCalculos
          ./FunctionalTest
          ./testCapacitancia

      # 6. Generar reporte de cobertura
      - name: Generate coverage report
        run: |
          cd Tarea7/build
          lcov --capture --directory . --output-file coverage.info
          lcov --remove coverage.info '/usr/*' '*/tests/*' --output-file coverage.filtered.info
          genhtml coverage.filtered.info --output-directory coverage-report

      # 7. Publicar el reporte de cobertura como artefacto (opcional)
      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: Tarea7/build/coverage-report
